config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :groups do
      resources :entities
    end
  end

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entities_group.rb
class EntitiesGroup < ApplicationRecord
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities, optional: true

  validates :name, presence: true
  validates :icon, presence: true

  def total_expenses_group
    entities.sum(:amount)
  end

  def icon_img
    icon_array = ['Housing', 'Transportation', 'Food', 'Utilities', 'Insurance', 'Healthcare', 'Savings & Investments',
                  'Personal Spendings', 'Recreation & Entertainment', 'Miscellaneous']
    something = ''
    icon_class = %w[house bicycle basket3 hammer shield-check heart piggy-bank cash-coin
                    joystick gem]
    icon_array.each_with_index do |i, index|
      something = icon_class[index] if icon == i
    end
    something
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :entities

  validates :name, presence: true

  def total_expenses_user
    entities.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def show
    @group = Group.find(params[:group_id])
    @entity = Entity.find(params[:id])
  end

  def new
    @user = current_user
    @group = Group.find(params[:group_id])
    @entity = Entity.new
  end

  def create
    user = current_user
    group = Group.find(params[:group_id])
    entity = user.entities.new(entity_params)

    if entity.save
      flash[:notice] = 'Entity created correctly'
      group.entities << entity
      redirect_to user_group_path(user.id, group.id)
    else
      flash[:error] = 'Entity not created'
      render :new
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @groups = @user.groups
    @total = @user.total_expenses_user
  end

  def show
    @user = current_user
    @group = Group.find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
    @total = @group.total_expenses_group
  end

  def new
    @user = current_user
    @group = Group.new
    @icons = ['Housing', 'Transportation', 'Food', 'Utilities', 'Insurance', 'Healthcare', 'Savings & Investments',
              'Personal Spendings', 'Recreation & Entertainment', 'Miscellaneous']
  end

  def create
    user = current_user
    group = user.groups.new(group_params)

    if group.save
      flash[:notice] = 'Group created correctly'
      redirect_to user_groups_path(user.id)
    else
      flash[:error] = 'Group not created'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/entities/new.html.erb
<header style="background-color: #3778c2;">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <div class="container-fluid">
        <%= link_to :back, class: "text-white" do %> 
          <i class="bi bi-arrow-left-short", style="font-size: 44px"></i>
        <% end %>
        <p class="navbar-brand m-0">NEW TRANSACTION</p>
        <button class="navbar-toggler invisible" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<%= form_with model: @entity, url: user_group_entities_path(@user.id, @group.id), method: :post do |form| %>
  <div class="mt-4 border-top border-bottom h-auto d-flex flex-column" >
    <div class="">
      <%= form.label :name, class: "d-none" %>
      <%= form.text_field :name, class: "p-2 ps-3 w-100 border-0", style: "color: #989da3" , placeholder: "Name", :required => true %>
    </div>
    <hr class="m-0 p-0 align-self-center" style="height:1px;width:90%;border-width:0;color:#989da3;background-color:#989da3">
    <div class="">
      <%= form.label :amount, class: "d-none" %>
      <%= form.number_field :amount, class: "p-2 ps-3 w-100 border-0", style: "color: #989da3" , placeholder: "Amount", step: 0.01, :required => true %>
    </div>
  </div>
  <div>
    <%= form.submit "Save", class: "m-3 btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/entities/show.html.erb
<header style="background-color: #3778c2;">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <div class="container-fluid">
        <%= link_to :back, class: "text-white" do %> 
          <i class="bi bi-arrow-left-short", style="font-size: 44px"></i>
        <% end %>
        <p class="navbar-brand m-0">DETAILS</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
              </li>
          </ul>
        </div>
      </div>
  </nav>
</header>
<div class="d-flex flex-column ms-3 me-3">
  <div class="mt-3 p-2 bg-white shadow-sm bg-body">
    <div class="d-flex align-items-center mb-2">
      <i class="#bi bi-<%= @group.icon_img %> me-3", style="font-size: 38px; color:#878a8f;"></i> 
      <div class="d-flex flex-column justify-content-between">
        <p class="mb-0" style="color:#434c55;"><%= @group.name %></p>
        <p class="mb-0" style="color: #989da3; font-size: 12px;"><%= @entity.created_at.strftime("%d %b %Y") %></p>
      </div>
    </div>
    <hr class="m-0 p-0 align-self-center" style="height:1px;width:100%;border-width:0;color:#989da3;background-color:#989da3">
    <div class="d-flex justify-content-between mt-3">
    <p class="mb-0" style="color:#878a8f;"><%= @entity.name %></p>
    <p class="mb-0" style="color:#434c55;">$<%= @entity.amount %></p>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<header style="background-color: #3778c2;">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <div class="container-fluid">
        <%= link_to :back, class: "text-white invisible" do %> 
          <i class="bi bi-arrow-left-short", style="font-size: 44px"></i>
        <% end %>
        <p class="navbar-brand m-0">CATEGORIES</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<div class="d-flex p-3 justify-content-between align-items-center bg-white border-bottom">
  <div><p class="m-0" style="color: #878a8f;">Total:</p></div>
  <div><p class="m-0" style="color: #434c55;">$<%= @total %></p></div>
</div>
<ul class="d-flex flex-column ms-3 me-3" style="">
  <% @groups.each do |group| %>
    <%= link_to user_group_path(user_id: @user.id, id: group.id) do %>
      <li class="mt-3 p-2 bg-white shadow-sm bg-body">
        <div class="float-start me-2">
         <i class="#bi bi-<%= group.icon_img %>", style="font-size: 34px; color:#878a8f;"></i> 
        </div>
        <div class="mt-2 d-flex justify-content-between">
          <div class="d-flex flex-column justify-content-between">
            <p class="mb-0" style="color: #878a8f;"><%= group.name %></p>
            <p class="mb-0" style="color: #989da3; font-size: 12px;"><%= group.created_at.strftime("%d %b %Y") %></p>
          </div>
          <div>
            <p class="mb-0" style="color: #434c55;">$<%= group.total_expenses_group %> </p>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
  <% if @groups.length == 0 %>
    <li>
      <p>There is no category yet. Please create one.</p>
    </li>
  <% end %>
</ul>
<%= link_to 'Add Category', new_user_group_path(@user.id), class: "m-3 btn btn-outline-primary" %>

app/views/groups/new.html.erb
<header style="background-color: #3778c2;">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <div class="container-fluid">
        <%= link_to :back, class: "text-white" do %> 
          <i class="bi bi-arrow-left-short", style="font-size: 44px"></i>
        <% end %>
        <p class="navbar-brand m-0">NEW CATEGORY</p>
        <button class="navbar-toggler invisible" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
              </li>
          </ul>
        </div>
      </div>
  </nav>
</header>
<%= form_with model: @group, url: user_groups_path(@user.id), method: :post do |form| %>
  <div class="mt-4 border-top border-bottom h-auto d-flex flex-column" >
    <div class="">
      <%= form.label :name, class: "d-none" %>
      <%= form.text_field :name, class: "p-2 ps-3 w-100 border-0", style: "color: #989da3" , placeholder: "Name", :required => true %>
    </div>
    <hr class="m-0 p-0 align-self-center" style="height:1px;width:90%;border-width:0;color:#989da3;background-color:#989da3">
    <div class="">
      <%= form.label :icon, class: "d-none" %>
      <%= form.select(:icon, options_for_select(@icons), {}, { :class => "p-2 ps-3 w-100 border-0 bg-white", :style => "color: #989da3" }) %>
    </div>
  </div>
  <div>
    <%= form.submit "Save", class: "m-3 btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<header style="background-color: #3778c2;">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <div class="container-fluid">
        <%= link_to user_groups_path(@user.id), class: "text-white" do %> 
          <i class="bi bi-arrow-left-short", style="font-size: 44px"></i>
        <% end %>
        <p class="navbar-brand m-0">TRANSACTIONS</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<div class="d-flex p-3 align-items-center shadow-lg" style="background-color: #3778c2">
  <div><p class="m-0 text-white">Category: <%= @group.name %></p></div>
</div>
<div class="d-flex p-3 justify-content-between align-items-center bg-white border-bottom">
  <div><p class="m-0" style="color: #878a8f;">Total:</p></div>
  <div><p class="m-0" style="color: #434c55;">$<%= @total %></p></div>
</div>
<ul class="d-flex flex-column ms-3 me-3" style="">
  <% @entities.each do |entity| %>
    <%= link_to user_group_entity_path(user_id: @user.id, group_id: @group.id, id: entity.id) do %>
      <li class="mt-3 p-2 bg-white shadow-sm bg-body">
        <div class="mt-2 d-flex justify-content-between">
          <div class="d-flex flex-column justify-content-between">
            <p class="mb-0" style="color: #878a8f;"><%= entity.name %></p>
            <p class="mb-0" style="color: #989da3; font-size: 12px;"><%= entity.created_at.strftime("%d %b %Y") %></p>
          </div>
          <div>
            <p class="mb-0" style="color: #434c55;">$<%= entity.amount %></p>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
  <% if @entities.length == 0 %>
    <li>
      <p>There is no transactions yet. Please create one.</p>
    </li>
  <% end %>
</ul>
<%= link_to 'Add Transaction', new_user_group_entity_path(@user.id, @group.id), class: "m-3 btn btn-outline-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<% if current_user %>
  <%= link_to 'groups', user_groups_path(@user.id) %>
<% else %>
  <div class="d-flex flex-column align-items-center justify-content-between p-4" style="background-color: #f1f3f2; position: absolute; bottom: 0; top: 0; left: 0; right: 0; z-index: -1;">
    <div style="position: relative; top: 40%;">
      <h1 style="color: #434c53">Budget Rails App</h1>
    </div>
    <div class="w-100 d-flex flex-column align-items-center">
      <%= link_to 'LOG IN', new_user_session_path, class: 'nav-link border border-primary rounded text-center text-white w-100', style: "background-color: #3778c2;" %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'nav-link text-secondary text-center mt-1', style: 'width: 90%' %>
    </div>
  </div>
<% end %>